<a href="https://colab.research.google.com/github/JUNGSEAHYUN04/2024-1-my-BDA/blob/main/tensorflowTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf

a = tf.constant(2, name = "tb_a")
b = tf.constant(3,name="tb_b")
x = tf.add(a,b,name ="tb_x")

with tf.Session() as sess:
  writer = tf.summary.FileWriter('./graphs',sess.graph)
  print(sess.run(x))
writer.close()




AttributeError: module 'tensorflow' has no attribute 'Session'

In [6]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [11]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.float32, shape=[3], name='a')
b = tf.constant([5,5,5],tf.float32,name="b")
c=tf.add(a,b)
init = tf.global_variables_initializer()
with tf.Session() as sess:
  sess.run(init)
  writer = tf.summary.FileWriter('./graphs',sess.graph)
  print(sess.run(c, feed_dict={a:[1,2,3]}))



[6. 7. 8.]


In [26]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c=tf.add(a,b)

init = tf.global_variables_initializer()

with tf.Session() as sess:
  sess.run(init)
  writer = tf.summary.FileWriter('./graphs',sess.graph)
  print(sess.run(c, feed_dict={a:[[1,2,3],[1,2,3],[1,2,3]], b:[[1,2,3],[1,2,3],[1,2,3]]}))

[[2 4 6]
 [2 4 6]
 [2 4 6]]


In [31]:
tf.disable_v2_behavior()

a = tf.placeholder(tf.int32)
b = tf.placeholder(tf.int32)
c=tf.add(a,b)
d= tf.subtract(a,b)
e= tf.multiply(a,b)
f = tf.divide(a,b)
init = tf.global_variables_initializer()

with tf.Session() as sess:
  sess.run(init)
  writer = tf.summary.FileWriter('./graphs',sess.graph)
  print('a+b =')
  print(sess.run(c, feed_dict={a:[[1,2,3],[1,2,3],[1,2,3]], b:[[1,2,3],[1,2,3],[1,2,3]]}))
  print()
  print('a-b =')
  print(sess.run(d, feed_dict={a:[[1,2,3],[1,2,3],[1,2,3]], b:[[1,2,3],[1,2,3],[1,2,3]]}))
  print()
  print('a*b =')
  print(sess.run(e, feed_dict={a:[[1,2,3],[1,2,3],[1,2,3]], b:[[1,2,3],[1,2,3],[1,2,3]]}))
  print()
  print('a/b =')
  print(sess.run(f, feed_dict={a:[[1,2,3],[1,2,3],[1,2,3]], b:[[1,2,3],[1,2,3],[1,2,3]]}))

a+b =
[[2 4 6]
 [2 4 6]
 [2 4 6]]

a-b =
[[0 0 0]
 [0 0 0]
 [0 0 0]]

a*b =
[[1 4 9]
 [1 4 9]
 [1 4 9]]

a/b =
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
